apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sparrow.fullname" . }}-node-deployment
  namespace: sparrow-{{ .Values.environment }}
  labels:
    app: {{ template "sparrow.fullname" . }}
    chart: {{ template "sparrow.chart" . }}
    component: "{{ .Values.api.fullname }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "sparrow.fullname" . }}
      component: "{{ .Values.api.name }}"
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "sparrow.fullname" . }}
        component: "{{ .Values.api.name }}"
        release: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: {{ template "sparrow.fullname" . }}-node
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
        imagePullPolicy: "{{ .Values.api.image.pullPolicy }}"
        env:
          - name: "SESSION_SECRET"
            value: keyboardcat
          - name: "GOOGLE_CLIENT_ID"
            value: test
        ports:
        - containerPort: 3000
        resources: {}
        workingDir: /usr/src/app
      restartPolicy: Always
status: {}

keel:
  policy: force
  trigger: poll
  pollSchedule: "@every 1m"
  images:
    - repository: image.repository
      tag: image.tag
