apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sparrow.fullname" . }}-api-deployment
  namespace: sparrow-{{ .Values.environment }}
  labels:
    app: {{ template "sparrow.fullname" . }}
    chart: {{ template "sparrow.chart" . }}
    component: "{{ .Values.api.fullname }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
spec:
  selector:
    matchLabels:
      app: {{ template "sparrow.fullname" . }}
      component: "{{ .Values.api.name }}"
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "sparrow.fullname" . }}
        component: "{{ .Values.api.name }}"
        release: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: {{ template "sparrow.fullname" . }}-api
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
        imagePullPolicy: "{{ .Values.api.image.pullPolicy }}"
        env:
          - name: SESSION_SECRET
            value: keyboardcat
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: sparrow-google-client-id
                key: GOOGLE_CLIENT_ID
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: sparrow-google-client-secret
                key: GOOGLE_CLIENT_SECRET
        ports:
        - containerPort: 3000
        resources: {}
        livenessProbe:
          httpGet:
            port: 3000
            path: /
          initialDelaySeconds: 3
          periodSeconds: 3
      restartPolicy: Always
status: {}
