apiVersion: v1
kind: Service
metadata:
  name: {{ template "sparrow.fullname" . }}-node-service
  namespace: sparrow-{{ .Values.environment }}
  labels:
    app: {{ template "sparrow.fullname" . }}
    chart: {{ template "sparrow.chart" . }}
    component: "{{ .Values.api.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: {{ template "sparrow.fullname" . }}
    component: "{{ .Values.api.name }}"
    release: {{ .Release.Name }}
status:
  loadBalancer: {}
