{{- if or (eq .Values.environment "staging") (eq .Values.environment "production") -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.environment }}-ingress
  namespace: {{ .Values.environment }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
{{- if eq .Values.environment "staging" }}
    - host: staging.sparrow.express
{{- end -}}
{{- if eq .Values.environment "production" }}
    - host: sparrow.express
{{- end }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ template "sparrow.fullname" . }}-nginx-service
            servicePort: 80
{{- end -}}
