apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sparrow.fullname" . }}-nginx-deployment
  namespace: sparrow-{{ .Values.environment }}
  labels:
    app: {{ template "sparrow.fullname" . }}
    chart: {{ template "sparrow.chart" . }}
    component: "{{ .Values.ui.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "sparrow.fullname" . }}
      component: "{{ .Values.ui.name }}"
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "sparrow.fullname" . }}
        component: "{{ .Values.ui.name }}"
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "sparrow.fullname" . }}-nginx
        image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
        imagePullPolicy: "{{ .Values.ui.image.pullPolicy }}"
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-proxy-config
      restartPolicy: Always
      volumes:
      - name: nginx-proxy-config
        configMap:
          name: {{ template "sparrow.fullname" . }}-configmap
status: {}
