apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sparrow.fullname" . }}-configmap
  namespace: sparrow-{{ .Values.environment }}
  labels:
    app: {{ template "sparrow.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.ui.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:

  default.conf: |
      server {
        listen 80;
        allow all;

        location / {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://release-name-sparrow-express-node-service;
        }

        location /api {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://release-name-sparrow-express-node-service;
        }

        error_page    500 502 503 504 /50x.html;
        location = /50x.html {
          root    /usr/share/nginx/html;
        }
      }
