apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sparrow.fullname" . }}-configmap
  namespace: sparrow-{{ .Values.environment }}
  labels:
    app: {{ template "sparrow.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.ui.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:

  default.conf: |
      server {
        listen 80;
        allow all;

        location / {
          resolver        8.8.8.8;
          proxy_pass      http://{{ template "sparrow.fullname" . }}-node-service:3000;
        }
      }
