apiVersion: v1
kind: Service
metadata:
  name: {{ template "sparrow.fullname" . }}-nginx-service
  namespace: sparrow-{{ .Values.environment }}
  labels:
    app: {{ template "sparrow.fullname" . }}
    chart: {{ template "sparrow.chart" . }}
    component: "{{ .Values.ui.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
{{- if eq .Values.environment "development" }}
    nodePort: {{ .Values.ui.service.nodePort }}
  type: NodePort
{{- end }}
  selector:
    app: {{ template "sparrow.fullname" . }}
    component: "{{ .Values.ui.name }}"
    release: {{ .Release.Name }}
status:
  loadBalancer: {}
