replicaCount: 1

environment: development

nginx:
  name: nginx
  image:
    repository: nginx
    tag: stable-alpine3.17
    pullPolicy: Always
  service:
    type: NodePort
    nodePort: 30000
  port: 80

ui:
  name: ui
  image:
    repository: jonathanleedev/sparrow-express-ui
    tag: latest
    pullPolicy: Never
  service:
    type: NodePort
    nodePort: 30001
  port: 80

api:
  name: api
  image:
    repository: jonathanleedev/sparrow-api
    tag: latest
    pullPolicy: Never
  service:
    type: NodePort
    nodePort: 30002
  session: keyboardcat
