replicaCount: 2

environment: production

ui:
  name: ui
  image:
    repository: nginx
    tag: latest
    pullPolicy: Always
  service:

api:
  name: api
  image:
    repository: node
    tag: latest
    pullPolicy: Always
