replicaCount: 2

environment: production

nginx:
  name: nginx
  image:
    repository: nginx
    tag: stable-alpine3.17
    pullPolicy: Always
  service:
    type: NodePort
    nodePort: 30000
  port: 80

ui:
  name: ui
  image:
    repository: nginx
    tag: latest
    pullPolicy: Always
  port: 80
  service:

api:
  name: api
  image:
    repository: node
    tag: latest
    pullPolicy: Always
