applicationName: sparrow-express
replicaCount: 1

environment:
  name: production
  hostPrefix:

ui:
  name: ui
  image:
    repository: jonathanleedev/sparrow-express-ui
    tag: 0.1.3
    pullPolicy: Always
  port: 80

api:
  name: api-old
  image:
    repository: jonathanleedev/sparrow-express-api-old
    tag: 0.1.3
    pullPolicy: Always
  port: 3000
