applicationName: sparrow-express

replicaCount: 1
environment: staging

ui:
  name: ui
  image:
    repository: jonathanleedev/sparrow-express-ui
    tag: latest
    pullPolicy: Never
  port: 80

api:
  name: api
  image:
    repository: jonathanleedev/sparrow-express-api
    tag: latest
    pullPolicy: Never
