replicaCount: 1

environment: staging

ui:
  name: ui
  image:
    repository: nginx
    tag: latest
    pullPolicy: Always

api:
  name: api
  image:
    repository: node
    tag: latest
    pullPolicy: Always
