name: '[PROD] Deploy'

on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
      - name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          token: '${{ github.token }}'
          chart: 'sparrow-production'
          namespace: 'default'
          release: sparrow-express
          value-files: './deployment/values/production-values.yml'
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
