name: SonarCloud Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install API Dependencies
        working-directory: ./services/api-old
        run: npm install
      - name: Run API Tests
        working-directory: ./services/api-old
        run: npm run test
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=jonathan-lee-devel_sparrow
            -Dsonar.organization=jonathan-lee-devel
            -Dsonar.sources=services/api-old/src
            -Dsonar.tests=services/api-old/src
            -Dsonar.inclusions=**
            -Dsonar.exclusions=**/*.spec.ts,**/index.ts,**/validations-chains/*.ts
            -Dsonar.test.inclusions=src/**/*.spec.ts,src/**/*.spec.tsx,src/**/*.test.ts,src/**/*.test.tsx
            -Dsonar.javascript.lcov.reportPaths=services/api-old/coverage/lcov.info
